@startuml

abstract class Pieces
{
    -description : string
    -numero_serie : int
    -reference : string
    +GetDescription(): string
    +GetNumeroSerie(): int
    +GetReference(): string
}

class Pieces_assemblage

class Piece_Moulee

class Piece_Usinee

Pieces <-- Piece_Moulee
Pieces <-- Pieces_assemblage
Pieces <-- Piece_Usinee
Pieces *-- Piece_SousEnsemble
Piece_SousEnsemble *-- Ensemble


class Piece_SousEnsemble
{
    -Dictionary<Pieces> : Dictionary<Pieces>
    +ListeComposant() : string

}

class Ensemble
{
    -Dictionary<Piece_SousEnsemble> : Dictionary<Piece_SousEnsemble>
    +ListeComposant() : string
}



@enduml