@startuml diagram

class Pieces
{
    -description : string
    -numero_serie : int
    -reference : string
    -Dictionary<Pieces, int> : Dictionary<Pieces,int>
    +ListeComposant() : string
    +GetDescription(): string
    +GetNumeroSerie(): int
    +GetReference(): string
}

class Pieces_assemblage
{
    -Test
}

class Piece_Moulee

class Piece_Usinee

class Piece_SousEnsemble

Pieces --> Piece_Moulee
Pieces <-- Pieces_assemblage
Pieces <-- Piece_Usinee
Pieces <-- Piece_SousEnsemble


@enduml